### ISSUE TITLE
Keep Saying FormatException: Unexpected character (at character 1) <!DOCTYPE html> IN IOS DEVICE.

### ISSUE THREAD

**Issue by drunisa007** [teranetsrl/oauth2_client#124]
Runner[1703:103288] [VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected character (at character 1)
<!DOCTYPE html>
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:612:36)
#5      JsonCodec.decode (dart:convert/json.dart:216:41)
#6      jsonDecode (dart:convert/json.dart:155:10)
#7      new AccessTokenResponse.fromHttpResponse (package:oauth2_client/access_token_response.dart:22:35)
#8      OAuth2Client.http2TokenResponse (package:oauth2_client/oauth2_client.dart:446:32)
#9      OAuth2Client.requestAccessToken (package:oauth2_client/oauth2_client.dart:259:12)
<asynchronous suspension>

**Comment by drunisa007** [comment]
closing this issue. i used wrong format.
