### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method read on ...flutter_secure_storage

### ISSUE THREAD

**Issue by rlfolden** [teranetsrl/oauth2_client#82]
I built your example targeting macos and get the following errors:

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method read on channel plugins.it_nomads.com/flutter_secure_storage)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
<asynchronous suspension>
#1      FlutterSecureStorage.read (package:flutter_secure_storage/flutter_secure_storage.dart:45:26)
<asynchronous suspension>
#2      SecureStorage.read (package:oauth2_client/src/secure_storage.dart:12:12)
<asynchronous suspension>
#3      TokenStorage.getToken (package:oauth2_client/src/token_storage.dart:20:36)
<asynchronous suspension>
#4      OAuth2Helper.getTokenFromStorage (package:oauth2_client/oauth2_helper.dart:105:12)
<asynchronous suspension>
#5      OAuth2Helper.getToken (package:oauth2_client/oauth2_helper.dart:80:19)
<asynchronous suspension>
#6      _MyHomePageState.authorize (package:oauth2_client_test/main.dart:93:23)
<asynchronous suspension>

I built Android Studio ver 4.1.2, Flutter 2.0.5, Dart 2.2.3 and MacOS ver 11.2.3

**Comment by okrad** [comment]
Hi @rlfolden, it seems to be a known issue that sometimes happens with flutter plugins. 
I never experienced it myself, but maybe you can find some (hopefully) useful information [here](https://github.com/flutter/flutter/issues/62006)...

**Comment by oceanebelle** [comment]
Encountered this error today and mine was resolved by adding additional dependencies in pubspec.yaml
e.g.
`
dependencies:
  oauth2_client: 2.2.0
  flutter_secure_storage: 4.2.0
  flutter_web_auth: 0.3.0
`

**Comment by okrad** [comment]
Thank you @oceanebelle for the suggestion!
@rlfolden, did you managed to solve your issue?
