### ISSUE TITLE
Custom Auth Client fails when fetching scope

### ISSUE THREAD

**Issue by oceanebelle** [teranetsrl/oauth2_client#86]
I have a custom client for azure / microsoft oauth 
```
class AzureOauth2Client extends OAuth2Client {
  AzureOauth2Client(): super(
      authorizeUrl: 'https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize', //Your service's authorization url
      tokenUrl: 'https://login.microsoftonline.com/consumers/oauth2/v2.0/token', //Your service access token url
      redirectUri: 'my.app://auth',
      customUriScheme: 'my.app'
  );
}
```

I've set my helper to be like this: 
```
    final HELPER = OAuth2Helper(new AzureOauth2Client(),
    grantType: OAuth2Helper.IMPLICIT_GRANT,
    clientId: 'ABCD',
    scopes: ['user.read', 'tasks.readwrite']);

```

When I run this, I get an error when the scope is being fetched. There is a mismatch between what the code expects vs what is returned. The string returned by the microsoft API is not split and turned into an array. the method is returning a string only.

Trace of the error.
```
/flutter ( 7989): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'String' is not a subtype of type 'List<String>?'
E/flutter ( 7989): #0      AccessTokenResponse.scope (package:oauth2_client/access_token_response.dart:131:12)
E/flutter ( 7989): #1      TokenStorage.insertToken (package:oauth2_client/src/token_storage.dart:66:42)
E/flutter ( 7989): <asynchronous suspension>
E/flutter ( 7989): #2      TokenStorage.addToken (package:oauth2_client/src/token_storage.dart:60:18)
E/flutter ( 7989): <asynchronous suspension>
E/flutter ( 7989): #3      OAuth2Helper.fetchToken (package:oauth2_client/oauth2_helper.dart:141:7)
E/flutter ( 7989): <asynchronous suspension>
E/flutter ( 7989): #4      OAuth2Helper.getToken (package:oauth2_client/oauth2_helper.dart:88:17)
E/flutter ( 7989): <asynchronous suspension>
E/flutter ( 7989): #5      OAuth2Helper._request (package:oauth2_client/oauth2_helper.dart:299:19)
```

My version 
dependencies:
  flutter:
    sdk: flutter
  oauth2_client: 2.2.0
  flutter_secure_storage: 4.2.0

**Comment by oceanebelle** [comment]
Additionally, when I use AUTHORIZATION_CODE, the sign in flow works fine but it doesn't seem to save the state so it's always authorizing.

**Comment by okrad** [comment]
Hi @oceanebelle, can you check the latest version (2.2.1)? I think your issue should be fixed...

**Comment by oceanebelle** [comment]
Thanks @okrad it does get beyond the issue now but I"m getting a storage related bug.

```
E/flutter ( 6146): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: Class 'String' has no instance method 'cast'.
E/flutter ( 6146): Receiver: "User.Read Tasks.ReadWrite Mail.Read Calendars.ReadWrite Notes.ReadWrite"
E/flutter ( 6146): Tried calling: cast<String>()
E/flutter ( 6146): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
E/flutter ( 6146): #1      TokenStorage.getToken.<anonymous closure> (package:oauth2_client/src/token_storage.dart:41:59)
E/flutter ( 6146): #2      Iterable.firstWhere (dart:core/iterable.dart:513:15)
E/flutter ( 6146): #3      TokenStorage.getToken (package:oauth2_client/src/token_storage.dart:33:40)
E/flutter ( 6146): <asynchronous suspension>
E/flutter ( 6146): #4      OAuth2Helper.getTokenFromStorage (package:oauth2_client/oauth2_helper.dart:105:12)
E/flutter ( 6146): <asynchronous suspension>
E/flutter ( 6146): #5      OAuth2Helper.getToken (package:oauth2_client/oauth2_helper.dart:80:19)
E/flutter ( 6146): <asynchronous suspension>
E/flutter ( 6146): #6      OAuth2Helper._request (package:oauth2_client/oauth2_helper.dart:299:19)
E/flutter ( 6146): <asynchronous suspension>
E/flutter ( 6146): #7      _LoginPageState.build.<anonymous closure> (package:mindspect_flutter/page/login.dart:71:30)
E/flutter ( 6146): <asynchronous suspension>
```

**Comment by outluch** [comment]
Fighting this issue 3hr already. 
My discovery: 
file `token_storage.dart`
```dart
  Future<AccessTokenResponse?> getToken(List<String> scopes) async {
    AccessTokenResponse? tknResp;

    final serializedStoredTokens = await storage.read(key);

    if (serializedStoredTokens != null) {
      final Map<String, dynamic> storedTokens =
          jsonDecode(serializedStoredTokens);

      final cleanScopes = clearScopes(scopes);

      var tknMap = storedTokens.values.firstWhere((tkn) {
        var found = false;

        if (cleanScopes.isEmpty) {
          //If the scopes are empty, onlty tokens granted to empty scopes are considered valid...
          found = (tkn['scope'] == null || tkn['scope'].isEmpty);
        } else {
          //...Otherwise look for a token granted to a superset of the requested scopes
          final tknCleanScopes = clearScopes(tkn['scope'].cast<String>()); // ERROR HERE. 
// We have tkn['scope'] = 'email profile' and it is string, not List. cast causes error


          if (tknCleanScopes.isNotEmpty) {
            var s1 = Set.from(tknCleanScopes);
            var s2 = Set.from(cleanScopes);
            found = s1.intersection(s2).length == cleanScopes.length;
          }
        }

        return found;
      }, orElse: () => null);

      if (tknMap != null) tknResp = AccessTokenResponse.fromMap(tknMap);
    }

    return tknResp;
  }

```

**Comment by okrad** [comment]
I just pushed a patch (not yet published on pub.dev), can you try it out?

Thank you!

**Comment by outluch** [comment]
Nice, it works now!! 
I was close to that, but didn't get it how to fix :)
```dart
  @override
  Map<String, dynamic> toMap() {
    return respMap;
    return {
      ...respMap,
      ...{'scope': scope}
    };
  }
```
